enabled: true
server_addr: 115.190.209.14
server_port: 8848
namespace_id: "b612b5b7-54de-4d44-b6d6-64d6091b2ea4"
group: dev
data_id: e2da04d1-be5b-4c87-8768-a95c948dfbde
username: ""
password: ""
timeout_ms: 5000
log_dir: logs/nacos
cache_dir: data/nacos/cache
log_level: info
fail_fast: false
watch: false
